# $Id: makefile.win32,v 2.3 1996/10/03 17:56:31 layer Exp $

!include <ntwin32.mak>

emacs_dir = $(emacs_dir)

.c{$(BLD)}.obj:
	$(CC) -c -nologo -DWIN32 $(CFLAGS) -Fo$@ $<

default:
	$(emacs_dir)\bin\emacs -batch -l fi-compile.el -kill

clman.exe:	clman.obj clmanaux.obj
	link -nologo -out:$@ -subsystem:console -entry:mainCRTStartup \
		clman.obj clmanaux.obj wsock32.lib
